interface ValidatorKey {
  network: string;
  mnemonic?: string[];
  privateKey?: string;
}

export const VALIDATOR_KEYS: Record<string, ValidatorKey> = {
  "pisco-1": {
    network: "Terra Testnet",
    mnemonic: [
      "coyote",
      "similar",
      "nuclear",
      "demand",
      "multiply",
      "shrimp",
      "build",
      "say",
      "rapid",
      "shoe",
      "purity",
      "remember",
      "load",
      "essay",
      "poet",
      "milk",
      "dad",
      "tilt",
      "pause",
      "judge",
      "position",
      "sun",
      "visit",
      "guess",
    ],
  },
  "evmos_9000-4": {
    network: "Evmos Testnet",
    mnemonic: [
      "helmet",
      "fog",
      "dizzy",
      "shove",
      "wave",
      "write",
      "pact",
      "silly",
      "someone",
      "quit",
      "then",
      "mind",
      "lecture",
      "version",
      "ready",
      "jelly",
      "method",
      "cross",
      "guide",
      "physical",
      "smart",
      "there",
      "abandon",
      "disease",
    ],
  },
  "comdex-test2": {
    network: "Comdex Testnet",
    mnemonic: [
      "endorse",
      "thought",
      "record",
      "annual",
      "title",
      "retreat",
      "boy",
      "physical",
      "news",
      "logic",
      "wheel",
      "vacuum",
      "bachelor",
      "range",
      "motor",
      "oval",
      "twin",
      "fine",
      "island",
      "snake",
      "field",
      "extra",
      "stick",
      "accident",
    ],
  },
  "injective-888": {
    network: "Injective Testnet",
    privateKey:
      "cc5cfa0441a8b38cf067d6064cda90a32f9ba135bc33a94166c4d83683f80954",
  },
};
